### ISSUE TITLE
Creating new theme @import url(false); 

### ISSUE THREAD

**Issue by AgnesR83** [mendix/ux-theming#4]
After creating a new theme.
Custom.css 
and lib.css 
start with:
@import url(false);
This creates an error.
[lib.txt](https://github.com/mendix/ux-theming/files/756816/lib.txt)
[custom.txt](https://github.com/mendix/ux-theming/files/756817/custom.txt)

**Comment by JelteMX** [comment]
How does your `lib.scss` and `custom.scss` look like? This does not seem to have something to do with my scripts here.

**Comment by AgnesR83** [comment]
Here are my lib.scss and custom.scss

**Comment by JeroenKesteloo** [comment]
I think this happens when you set your $font-family-import to 'false' in your custom-variables.scss.

// Font Family Import
$font-family-import: 	false;
@import url($font-family-import);

In your custom.scss (first line) it will import the custom-variables.scss where it will lead to @import url(false); in your custom.css.

**Comment by RCatersels** [comment]
I do recognize this and created a ticket for it. I created a new base theme for a client that migrated from Mx4 to Mx6. But this base theme without any adjustments would throw 404 errors in the console. Created a ticket for this (49129).

Regards,

Ronald
